\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename boots-puzzle.info
@settitle Adventures in Boots-Puzzle
@c %**end of header

@c copyright info
@copying
This is the manual for the Boots-Puzzle Engine.

Copyright @copyright{} 2008 Pierre-Henri Trivier.
@end copying

@c title page
@titlepage
@title Adventures in Boots-Puzzle
@subtitle Does anybody know Boots ?
@author Pierre-Henri Trivier (@email{phtrivier@@yahoo.fr})

@c copyright page
@page
@vskip 0pt plus 1fill
@insertcopying
@end titlepage

@c table of contents
@contents

@c -------------------------------

@c top node
@ifnottex
@node Top, Introduction, (dir), (dir)
@top Adventures in Boots-Puzzle

This is the manual for people willing to create new adventures to play
with the boots-puzzle program.
@end ifnottex

@c ------------------------



@c Body of the document
@menu
* Introduction::                
* Adventures::                  
* Levels::                      
* Puzzles::                     
* Stories::                     
* Plugins::                     
* Index::                       
@end menu

@include introduction.texinfo
@include adventures.texinfo
@include levels.texinfo
@include puzzles.texinfo
@include stories.texinfo
@include plugins.texinfo
@include index.texinfo

@bye

