* RatLab
A boots-puzzle adventure.

* Scenario 

'ratlab' is the latest brew of real-TV show. People are followed
trying to solved tricky puzzles involving alternative displacement
techniques. (TODO : acronym pun with boots)

The story is told by "The Producer" (hint : could be fun to meet the producer in the end)

Stages are : 

1) casting
2) a few days to learn how to play
3) a few rounds of elimination (but you stay inside the show)
4) a round when you are excluded from the show
5) a final round where you try to unmask how completely 'truqué' (hoaxed, arranged, fixed?) the show was
6) final showdown with the Producer

Extra characters 

- you, eager to play and to win, only interested in fame and money, some kind of a anti-hero
- the host, completely clueless, provides some of the fun and
  constently make stupid remarks. Also, always confuses the show with other known ones, so 
  you can make plenty of inside jokes...
- the assistant (would probably understand the whole point of the show if he had a second between getting coffee for the
  producer and finding a girl for the host - or the other way around)
- the producer, cynical, treating all participants like meat, showing up occasionnaly to fire someone

Places

- the player's room (I like the idea that you come back to this place from time to time, and that you
